import { describe, it, expect, beforeEach, vi } from 'vitest';
import request from 'supertest';
import { mockPrisma } from '../setup.js';

let app: any;

beforeEach(async () => {
  vi.clearAllMocks();
  // Default: no QBO-connected locations, so getMissingGlAccountWarnings()
  // short-circuits to []. Individual tests override this when they need to
  // exercise the warning narrowing logic.
  mockPrisma.location.findMany.mockResolvedValue([]);
  const mod = await import('../../src/index.js');
  app = mod.default;
});

const buildLocation = (id: string, name: string, qboConnected = false) => ({
  id,
  name,
  qboAccessToken: qboConnected ? 'tok' : null,
  qboRealmId: qboConnected ? 'realm' : null,
});

const buildRentalProduct = (overrides: any = {}) => ({
  id: 'rp-1',
  tenantId: 'test-tenant-id',
  name: 'Kayak — half day',
  category: 'kayak',
  glAccountId: null,
  active: true,
  ...overrides,
});

describe('GET /api/settings/catalog/products-summary', () => {
  it('expands rental products across every location when no locationId', async () => {
    // Two locations on the tenant; tenant-wide call (no locationId).
    // Order matters: the route's Promise.all issues the rentals-locations
    // findMany first, then the warnings helper issues a second findMany
    // filtered to QBO-connected locations only.
    mockPrisma.location.findMany
      .mockResolvedValueOnce([
        buildLocation('loc-a', 'North Marina'),
        buildLocation('loc-b', 'South Marina'),
      ])
      .mockResolvedValueOnce([]); // warnings helper: no QBO locs
    mockPrisma.dockageRate.findMany.mockResolvedValue([]);
    mockPrisma.serviceFee.findMany.mockResolvedValue([]);
    mockPrisma.rentalProduct.findMany.mockResolvedValue([buildRentalProduct()]);
    mockPrisma.glAccount.findMany.mockResolvedValue([]);
    mockPrisma.dockageRateGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.serviceFeeGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.rentalProductGlMapping.findMany.mockResolvedValue([]);

    const res = await request(app).get('/api/settings/catalog/products-summary');

    expect(res.status).toBe(200);
    expect(res.body.data.rentalProducts).toHaveLength(1);
    // Tenant-wide mode keeps the full per-location grid.
    expect(res.body.data.rentalProducts[0].perLocation).toHaveLength(2);
    expect(res.body.data.locations).toHaveLength(2);
    // Both locations lack a revenue mapping → unconfigured count = 2.
    expect(res.body.data.unconfiguredCount).toBe(2);
  });

  it('narrows perLocation, locations stay full, and unconfiguredCount shrinks when locationId given', async () => {
    mockPrisma.location.findMany
      .mockResolvedValueOnce([
        buildLocation('loc-a', 'North Marina'),
        buildLocation('loc-b', 'South Marina'),
      ])
      .mockResolvedValueOnce([]); // warnings helper: no QBO locs
    mockPrisma.dockageRate.findMany.mockResolvedValue([]);
    mockPrisma.serviceFee.findMany.mockResolvedValue([]);
    mockPrisma.rentalProduct.findMany.mockResolvedValue([buildRentalProduct()]);
    mockPrisma.glAccount.findMany.mockResolvedValue([]);
    mockPrisma.dockageRateGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.serviceFeeGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.rentalProductGlMapping.findMany.mockResolvedValue([]);

    const res = await request(app).get(
      '/api/settings/catalog/products-summary?locationId=loc-a',
    );

    expect(res.status).toBe(200);
    // Single-location mode collapses perLocation to one entry.
    expect(res.body.data.rentalProducts[0].perLocation).toHaveLength(1);
    expect(res.body.data.rentalProducts[0].perLocation[0].locationId).toBe('loc-a');
    // The full locations list is still returned so the UI can populate
    // location-aware controls regardless of which one is selected.
    expect(res.body.data.locations).toHaveLength(2);
    // Unconfigured count is now narrowed to just loc-a's gap (was 2).
    expect(res.body.data.unconfiguredCount).toBe(1);
  });

  it('filters missingMappingWarnings to the selected location', async () => {
    // QBO-connected locations exist → warnings will be generated by the
    // resolver. We mock all the resolver's prisma calls so two locations
    // each report a "missing revenue" item for the same product.
    mockPrisma.location.findMany
      // First call (Promise.all → locationsForRentals): full shape with
      // QBO tokens so the route flags both as qboConnected.
      .mockResolvedValueOnce([
        buildLocation('loc-a', 'North', true),
        buildLocation('loc-b', 'South', true),
      ])
      // Second call (getMissingGlAccountWarnings): trimmed shape, only
      // QBO-connected locations.
      .mockResolvedValueOnce([
        { id: 'loc-a', name: 'North' },
        { id: 'loc-b', name: 'South' },
      ]);
    mockPrisma.product.findMany.mockResolvedValue([
      {
        id: 'p-1',
        name: 'Bilge Cleaner',
        trackInventory: false,
        productCategoryId: null,
      },
    ]);
    mockPrisma.productGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.productCategoryGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.productCategory.findMany.mockResolvedValue([]);
    mockPrisma.dockageRate.findMany.mockResolvedValue([]);
    mockPrisma.dockageRateGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.serviceFee.findMany.mockResolvedValue([]);
    mockPrisma.serviceFeeGlMapping.findMany.mockResolvedValue([]);
    mockPrisma.rentalProduct.findMany.mockResolvedValue([]);
    mockPrisma.glAccount.findMany.mockResolvedValue([]);
    mockPrisma.rentalProductGlMapping.findMany.mockResolvedValue([]);

    const res = await request(app).get(
      '/api/settings/catalog/products-summary?locationId=loc-a',
    );

    expect(res.status).toBe(200);
    // Both loc-a and loc-b would have warnings; the route must filter to
    // only loc-a so the banner doesn't list other marinas the operator
    // isn't currently looking at.
    expect(res.body.data.missingMappingWarnings.length).toBeGreaterThan(0);
    for (const w of res.body.data.missingMappingWarnings) {
      expect(w.locationId).toBe('loc-a');
    }
  });
});
