// ─────────────────────────────────────────────────────────────────────────────
// Report Catalog
//
// Walks the Prisma schema at startup and emits a JSON catalog describing
// every reportable model, its fields, and its relations. This is the
// foundation for the Universal Report Builder — the builder UI lets a tenant
// admin pick a model, tick on fields, and submit a query spec; the engine
// (future work) validates the spec against this catalog before running the
// query.
//
// The catalog is generated by parsing prisma/schema.prisma as text. Prisma's
// generated client doesn't expose a stable DMMF in v6, and adding the
// internals package as a runtime dep is more weight than the parser saves.
// Schemas are regular enough that ~80 lines of regex covers every model in
// our codebase today, and the result is deterministic and easy to diff.
// ─────────────────────────────────────────────────────────────────────────────

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

export type FieldKind = "scalar" | "relation" | "enum" | "json";

export interface CatalogField {
  name: string;
  type: string;
  kind: FieldKind;
  optional: boolean;
  isList: boolean;
  isId: boolean;
  hasDefault: boolean;
  isUnique: boolean;
  // Marked sensitive based on a small allowlist (hashed keys, raw payloads,
  // signatures, Stripe IDs). The query engine will refuse to expose these
  // unless the platform layer explicitly allows them. Heuristic-only; the
  // real allowlist will live in a database table in a later phase.
  sensitive: boolean;
}

export interface CatalogModel {
  name: string;
  tableName: string | null;
  fields: CatalogField[];
  fieldCount: number;
  relationCount: number;
  // True if the model carries a tenantId column. The query engine appends
  // a tenant scope to every query that touches a tenant-scoped model.
  tenantScoped: boolean;
  locationScoped: boolean;
}

export interface ReportCatalog {
  generatedAt: string;
  schemaSource: string;
  modelCount: number;
  fieldCount: number;
  models: CatalogModel[];
}

// Field names we never want to expose to a custom report. The list is small
// and well-known — secrets, raw third-party payloads, signature material.
const SENSITIVE_FIELD_PATTERNS = [
  /hashedkey/i,
  /\bsecret\b/i,
  /signature/i,
  /payloadjson/i,
  /stripecharge/i,
  /stripepaymentintent/i,
  /stripecustomer/i,
  /stripesubscription/i,
  /clerkid/i,
  /webhooksecret/i,
];

// Prisma scalar types we treat as plain values. Anything else is either a
// declared enum, a relation, or an unsupported type.
const SCALAR_TYPES = new Set([
  "String", "Boolean", "Int", "BigInt", "Float", "Decimal",
  "DateTime", "Bytes",
]);

function isSensitive(fieldName: string): boolean {
  return SENSITIVE_FIELD_PATTERNS.some((re) => re.test(fieldName));
}

function classifyField(rawType: string, enumNames: Set<string>): FieldKind {
  if (rawType === "Json") return "json";
  if (SCALAR_TYPES.has(rawType)) return "scalar";
  if (enumNames.has(rawType)) return "enum";
  return "relation";
}

function parseEnums(schema: string): Set<string> {
  const names = new Set<string>();
  const re = /^enum\s+(\w+)\s*\{/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(schema)) !== null) {
    names.add(m[1]);
  }
  return names;
}

function parseModel(block: string, enumNames: Set<string>): CatalogModel {
  const lines = block.split("\n");
  const nameMatch = lines[0].match(/^model\s+(\w+)/);
  const name = nameMatch ? nameMatch[1] : "Unknown";

  let tableName: string | null = null;
  const fields: CatalogField[] = [];

  for (const raw of lines.slice(1)) {
    const line = raw.trim();
    if (!line || line.startsWith("//")) continue;
    if (line === "}") break;

    // @@map("snake_case")
    const mapMatch = line.match(/^@@map\("([^"]+)"\)/);
    if (mapMatch) {
      tableName = mapMatch[1];
      continue;
    }
    // skip @@index, @@unique, etc.
    if (line.startsWith("@@")) continue;

    // Field line: "name Type[?] [attributes...]"
    const fieldMatch = line.match(/^(\w+)\s+(\w+)(\[\])?(\?)?\s*(.*)$/);
    if (!fieldMatch) continue;
    const [, fname, baseType, list, optional, rest] = fieldMatch;
    // Skip relation-resolver fields that aren't database-backed:
    // these are lines like `customer Customer @relation(fields: [customerId], references: [id])`.
    // We still record them as relations (the UI will show "follow to Customer")
    // but mark them as non-scalar.
    const kind = classifyField(baseType, enumNames);
    fields.push({
      name: fname,
      type: baseType,
      kind,
      optional: !!optional,
      isList: !!list,
      isId: /@id\b/.test(rest),
      hasDefault: /@default\(/.test(rest),
      isUnique: /@unique\b/.test(rest),
      sensitive: isSensitive(fname),
    });
  }

  const relationCount = fields.filter((f) => f.kind === "relation").length;
  const tenantScoped = fields.some((f) => f.name === "tenantId");
  const locationScoped = fields.some((f) => f.name === "locationId");

  return {
    name,
    tableName,
    fields,
    fieldCount: fields.length,
    relationCount,
    tenantScoped,
    locationScoped,
  };
}

function buildCatalog(schemaPath: string): ReportCatalog {
  const schema = readFileSync(schemaPath, "utf8");
  const enumNames = parseEnums(schema);

  const models: CatalogModel[] = [];
  // Split on model boundaries. Each block starts with `model X {` and ends
  // with the matching `}` at column zero — Prisma's formatter guarantees
  // this for our schema today.
  const re = /^model\s+\w+\s*\{[\s\S]*?^\}/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(schema)) !== null) {
    models.push(parseModel(m[0], enumNames));
  }

  return {
    generatedAt: new Date().toISOString(),
    schemaSource: schemaPath,
    modelCount: models.length,
    fieldCount: models.reduce((sum, m) => sum + m.fieldCount, 0),
    models: models.sort((a, b) => a.name.localeCompare(b.name)),
  };
}

// Lazily build the catalog on first access and cache for the lifetime of
// the process. The schema only changes on migration; a process restart
// happens at deploy time so the cache is naturally invalidated.
let cached: ReportCatalog | null = null;

export function getReportCatalog(): ReportCatalog {
  if (!cached) {
    const schemaPath = resolve(process.cwd(), "prisma/schema.prisma");
    cached = buildCatalog(schemaPath);
  }
  return cached;
}

// Test seam — exposed so tests can build a catalog against a fixture path
// without polluting the lazy cache.
export function buildCatalogFromPath(schemaPath: string): ReportCatalog {
  return buildCatalog(schemaPath);
}
